[package]
name = "krad"
version = "0.1.0"
edition = "2018"

[lib]
name = "krad"
path = "src/lib.rs"

[[bin]]
name = "radkatinate"
path = "src/bin.rs"

[dependencies]
anyhow = "1"
thiserror = "1"
nom = "6"
encoding = "0"