[package]
name = "kanji-api"
version = "0.1.0"
edition = "2018"

[lib]
name = "kanji_api"
path = "src/lib.rs"

[[bin]]
name = "kanji_api_bin"
path = "src/bin.rs"

[dependencies]
anyhow = "1"
thiserror = "1"
nom = "6"