[package]
name = "kradical"
version = "0.1.0"
edition = "2018"

[lib]
name = "kradical"
path = "src/lib.rs"

[[bin]]
name = "jis_to_utf8"
path = "src/bin.rs"

[dependencies]
thiserror = "1"
nom = "6"
encoding = "0"
unicode-segmentation = "1"